[dependencies]
"php/php" = "=8.0.10"

[fs]
"/app" = "app"

[[command]]
name = "run"
module = "php/php:php"
runner = "wasi"
[command.annotations.wasi]
env = ["USE_ZEND_ALLOC=0"]
main-args = ["-t", "/app", "-S", "localhost:8080"]
